name: deprem_destek
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 2.19.1
  flutter: 3.7.1

dependencies:
  cloud_firestore: ^4.5.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  google_geocoding_api: ^1.3.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  reactive_forms: ^14.1.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
